/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
Title: Low Poly Planet Earth
*/
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { useMemo } from 'react'
import { CENTER } from '@/config'

export default function Earth({
  position: [lat, lng] = CENTER,
}: {
  position?: [number, number]
}) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const rotation = useMemo(() => getEarthRotation(lat, lng), [lat, lng])
  return (
    <group rotation={rotation} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // @ts-ignore
        geometry={nodes.Object_Planet_0.geometry}
        material={materials.Planet}
        position={[0, 0, 0]}
        rotation={modelCorrectionEuler}
      />
    </group>
  )
}

useGLTF.preload('/scene.gltf')

const modelCorrectionEuler = new THREE.Euler(Math.PI, Math.PI / -2, Math.PI, 'XYZ')

function getEarthRotation(lat: number, lon: number): THREE.Euler {
  const φ = THREE.MathUtils.degToRad(lat)
  const θ = THREE.MathUtils.degToRad(-lon)
  return new THREE.Euler(φ, θ, 0, 'XYZ')
}
